"""create recruiters and refresh_tokens tables

Revision ID: 400698eae65e
Revises: 9454b252149b
Create Date: 2026-01-23 13:30:53.131282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '400698eae65e'
down_revision: Union[str, Sequence[str], None] = '9454b252149b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('idx_resumes_email'), table_name='resumes')
    op.drop_index(op.f('idx_resumes_id'), table_name='resumes')
    op.drop_index(op.f('idx_resumes_location'), table_name='resumes')
    op.drop_index(op.f('idx_resumes_name'), table_name='resumes')
    op.drop_index(op.f('idx_resumes_parsed_data_gin'), table_name='resumes', postgresql_using='gin')
    op.drop_index(op.f('idx_resumes_search_text_gin'), table_name='resumes', postgresql_using='gin')
    op.drop_table('resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('search_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_edited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('parsing_quality', sa.VARCHAR(length=20), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_index(op.f('idx_resumes_search_text_gin'), 'resumes', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(search_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_resumes_parsed_data_gin'), 'resumes', ['parsed_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_resumes_name'), 'resumes', ['name'], unique=False)
    op.create_index(op.f('idx_resumes_location'), 'resumes', ['location'], unique=False)
    op.create_index(op.f('idx_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('idx_resumes_email'), 'resumes', ['email'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
